BEGIN;

DROP TABLE IF EXISTS log_operazioni;
DROP TABLE IF EXISTS convenzioni;
DROP TABLE IF EXISTS provvedimenti_mancato_utilizzo;
DROP TABLE IF EXISTS utilizzi_effettivi;
DROP TABLE IF EXISTS indisponibilita_sopravvenute;
DROP TABLE IF EXISTS concertazione_proposta_slot;
DROP TABLE IF EXISTS concertazione_proposta_parti;
DROP TABLE IF EXISTS concertazione_proposte;
DROP TABLE IF EXISTS sorteggio_candidati;
DROP TABLE IF EXISTS sorteggi;
DROP TABLE IF EXISTS assegnazioni;
DROP TABLE IF EXISTS elaborazioni;
DROP TABLE IF EXISTS coefficienti_associazione;
DROP TABLE IF EXISTS fabbisogni_riconosciuti;
DROP TABLE IF EXISTS osservazioni_istruttoria;
DROP TABLE IF EXISTS richieste_giornata_gara;
DROP TABLE IF EXISTS blocco_allenamento_slot;
DROP TABLE IF EXISTS blocchi_allenamento_richiesti;
DROP TABLE IF EXISTS preferenze;
DROP TABLE IF EXISTS domanda_impianti_compatibili;
DROP TABLE IF EXISTS domanda_discipline;
DROP TABLE IF EXISTS domande;
DROP TABLE IF EXISTS utenti_backoffice CASCADE;
DROP TABLE IF EXISTS abilitazioni;
DROP TABLE IF EXISTS associazioni_documenti;
DROP TABLE IF EXISTS associazioni;
DROP TABLE IF EXISTS persone_fisiche;
DROP TABLE IF EXISTS slot_settimana_tipo;
DROP TABLE IF EXISTS spazio_disciplina_compatibile;
DROP TABLE IF EXISTS discipline_sportive;
DROP TABLE IF EXISTS spazi_sportivi;
DROP TABLE IF EXISTS impianti;
DROP TABLE IF EXISTS istituzioni_scolastiche;
DROP TABLE IF EXISTS caa_scaglioni;
DROP TABLE IF EXISTS crs_scaglioni;
DROP TABLE IF EXISTS incremento_squadre_scaglioni;
DROP TABLE IF EXISTS classi_attivita;
DROP TABLE IF EXISTS csd_scaglioni;
DROP TABLE IF EXISTS parametrico_versioni;
DROP TABLE IF EXISTS impostazioni_sistema;
DROP TABLE IF EXISTS stagioni_sportive;

COMMIT;
